# -*- coding: utf-8 -*-
"""code-challenge_minicourse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKMpf5l-4KiJRmxbtemt0PYWhZRBbFIb

# **Python Code Challenge**
"""

product = ["Apple", "Orange", 100, "Grape", 120.33, "Cherry", 13.00, "Pear", 500, "Melon", "Strawberry"]

str_items = []
num_items = []

for item in product:
    if isinstance(item, str):
      str_items.append(item)
    elif isinstance(item, int) or isinstance(item, float):
      num_items.append(item)

"""**Create separate lists of strings and numbers**"""

print(str_items)

print(num_items)

"""**Sort the list in ascending order**"""

str_items.sort()
print(str_items)

#sort : default urutan ascending dari rendah ke tinggi/ kecil ke besar, dalam abjad berarti dari a ke z

"""**Sort the list in descending order**"""

str_items.sort(reverse=True)
print(str_items)

"""**Sort the number list from lowest to highest**"""

num_items.sort()
print(num_items)

"""**Sort the number list from highest to lowest**"""

num_items.sort(reverse=True)
print(num_items)